sonar.projectKey=foundlost
sonar.projectName=FOUNDLOST
sonar.projectVersion=1.0

sonar.sources=src,backend
sonar.tests=test
sonar.test.inclusions=test/**/*.test.cjs
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,backend/assets/**,**/.env,**/*.sql
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.node.maxspace=4096
